module ScopeEnforceable
  def context: () -> GraphQL::Query::Context

  #: () -> bool
  def can_search?: () -> bool

  #: () -> void
  def require_search!: () -> void

  #: () -> bool
  def can_upload?: () -> bool

  #: () -> void
  def require_upload!: () -> void

  private

  #: () -> bool
  def session_user?: () -> bool
end
