# DB schema: configs table (single-table inheritance via `type` column)
class Config < ApplicationRecord
  attr_accessor type: String

  self.@setting: Config::Setting?

  def self.setting: () -> Config::Setting
                  | () { (Config::Setting) -> void } -> Config::Setting

  def self.newest: () -> Config

  #: () -> Config::Serializer
  def settings: () -> Config::Serializer

  #: (::Hash[untyped, untyped] hash) -> void
  def settings=: (::Hash[String | Symbol, untyped] hash) -> void
end
