# DB schema: users table
class User < ApplicationRecord
  attr_accessor admin: bool
  attr_accessor email: String
  attr_accessor encrypted_password: String
  attr_accessor remember_created_at: ActiveSupport::TimeWithZone?
  attr_accessor reset_password_sent_at: ActiveSupport::TimeWithZone?
  attr_accessor reset_password_token: String?

  def access_tokens: () -> untyped

  #: () -> bool
  def admin?: () -> bool

  def self.any?: () -> bool
  def self.none?: () -> bool
end
