class Config::VideosController < ApplicationController
  @config_video: Config::Video

  #: () -> void
  def new: () -> void

  #: () -> void
  def create: () -> void

  #: () -> void
  def edit: () -> void

  #: () -> void
  def update: () -> void

  private

  def edit_config_video_path: () -> String
  def new_config_video_path: () -> String

  #: () -> ActionController::Parameters
  def video_params: () -> ActionController::Parameters
end
