# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> ::String
  def preview_view_components_path: (*untyped) -> ::String
  def preview_view_component_path: (*untyped) -> ::String
  def rails_info_properties_path: (*untyped) -> ::String
  def rails_info_routes_path: (*untyped) -> ::String
  def rails_info_notes_path: (*untyped) -> ::String
  def rails_info_path: (*untyped) -> ::String
  def mission_control_jobs_path: (*untyped) -> ::String
  def graphiql_rails_path: (*untyped) -> ::String
  def graphql_path: (*untyped) -> ::String
  def tus_server_path: (*untyped) -> ::String
  def rails_health_check_path: (*untyped) -> ::String
  def setup_path: (*untyped) -> ::String
  def new_user_session_path: (*untyped) -> ::String
  def user_session_path: (*untyped) -> ::String
  def destroy_user_session_path: (*untyped) -> ::String
  def oauth_token_path: (*untyped) -> ::String
  def oauth_revoke_path: (*untyped) -> ::String
  def oauth_introspect_path: (*untyped) -> ::String
  def oauth_applications_path: (*untyped) -> ::String
  def new_oauth_application_path: (*untyped) -> ::String
  def edit_oauth_application_path: (*untyped) -> ::String
  def oauth_application_path: (*untyped) -> ::String
  def oauth_authorized_applications_path: (*untyped) -> ::String
  def oauth_authorized_application_path: (*untyped) -> ::String
  def oauth_token_info_path: (*untyped) -> ::String
  def oauth_device_codes_create_path: (*untyped) -> ::String
  def oauth_device_authorizations_index_path: (*untyped) -> ::String
  def oauth_device_authorizations_authorize_path: (*untyped) -> ::String
  def grant_devices_path: (*untyped) -> ::String
  def devices_path: (*untyped) -> ::String
  def device_path: (*untyped) -> ::String
  def new_config_video_path: (*untyped) -> ::String
  def edit_config_video_path: (*untyped) -> ::String
  def config_video_path: (*untyped) -> ::String
  def reset_and_resync_video_blobs_path: (*untyped) -> ::String
  def video_blobs_path: (*untyped) -> ::String
  def uploads_path: (*untyped) -> ::String
  def api_docs_path: (*untyped) -> ::String
  def root_path: (*untyped) -> ::String
  def turbo_recede_historical_location_path: (*untyped) -> ::String
  def turbo_resume_historical_location_path: (*untyped) -> ::String
  def turbo_refresh_historical_location_path: (*untyped) -> ::String
  def rails_postmark_inbound_emails_path: (*untyped) -> ::String
  def rails_relay_inbound_emails_path: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_path: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_path: (*untyped) -> ::String
  def rails_conductor_inbound_emails_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def rails_mailers_url: (*untyped) -> ::String
  def preview_view_components_url: (*untyped) -> ::String
  def preview_view_component_url: (*untyped) -> ::String
  def rails_info_properties_url: (*untyped) -> ::String
  def rails_info_routes_url: (*untyped) -> ::String
  def rails_info_notes_url: (*untyped) -> ::String
  def rails_info_url: (*untyped) -> ::String
  def mission_control_jobs_url: (*untyped) -> ::String
  def graphiql_rails_url: (*untyped) -> ::String
  def graphql_url: (*untyped) -> ::String
  def tus_server_url: (*untyped) -> ::String
  def rails_health_check_url: (*untyped) -> ::String
  def setup_url: (*untyped) -> ::String
  def new_user_session_url: (*untyped) -> ::String
  def user_session_url: (*untyped) -> ::String
  def destroy_user_session_url: (*untyped) -> ::String
  def oauth_token_url: (*untyped) -> ::String
  def oauth_revoke_url: (*untyped) -> ::String
  def oauth_introspect_url: (*untyped) -> ::String
  def oauth_applications_url: (*untyped) -> ::String
  def new_oauth_application_url: (*untyped) -> ::String
  def edit_oauth_application_url: (*untyped) -> ::String
  def oauth_application_url: (*untyped) -> ::String
  def oauth_authorized_applications_url: (*untyped) -> ::String
  def oauth_authorized_application_url: (*untyped) -> ::String
  def oauth_token_info_url: (*untyped) -> ::String
  def oauth_device_codes_create_url: (*untyped) -> ::String
  def oauth_device_authorizations_index_url: (*untyped) -> ::String
  def oauth_device_authorizations_authorize_url: (*untyped) -> ::String
  def grant_devices_url: (*untyped) -> ::String
  def devices_url: (*untyped) -> ::String
  def device_url: (*untyped) -> ::String
  def new_config_video_url: (*untyped) -> ::String
  def edit_config_video_url: (*untyped) -> ::String
  def config_video_url: (*untyped) -> ::String
  def reset_and_resync_video_blobs_url: (*untyped) -> ::String
  def video_blobs_url: (*untyped) -> ::String
  def uploads_url: (*untyped) -> ::String
  def api_docs_url: (*untyped) -> ::String
  def root_url: (*untyped) -> ::String
  def turbo_recede_historical_location_url: (*untyped) -> ::String
  def turbo_resume_historical_location_url: (*untyped) -> ::String
  def turbo_refresh_historical_location_url: (*untyped) -> ::String
  def rails_postmark_inbound_emails_url: (*untyped) -> ::String
  def rails_relay_inbound_emails_url: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_url: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_url: (*untyped) -> ::String
  def rails_conductor_inbound_emails_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
