class ApplicationController < ActionController::Base
  def current_user: () -> User?
  def authenticate_user!: () -> void
  def sign_in: (Symbol scope, untyped resource) -> void
  def user_signed_in?: () -> bool

  def self.stale_when_importmap_changes: () -> void

  def setup_path: () -> String
  def root_path: () -> String

  private

  #: () -> void
  def authenticate_or_setup!: () -> void
end
