class DevicesController < ApplicationController
  @tokens: untyped

  #: () -> void
  def index: () -> void

  #: () -> void
  def destroy: () -> void

  private

  def devices_path: () -> String

  #: () -> untyped
  def find_token: () -> untyped
end
