class GraphqlController < ApplicationController
  @current_user: User?
  @doorkeeper_token: untyped
  @doorkeeper_access_token: untyped

  #: () -> void
  def execute: () -> void

  private

  #: () -> void
  def authenticate_graphql_user!: () -> void

  #: (untyped variables_param) -> ::Hash[String, untyped]
  def prepare_variables: (untyped variables_param) -> ::Hash[String, untyped]

  #: (StandardError e) -> void
  def handle_error_in_development: (StandardError e) -> void

  def logger: () -> ::Logger

  #: () -> untyped
  def doorkeeper_access_token: () -> untyped

  #: () -> bool
  def doorkeeper_token_request?: () -> bool
end
