class SetupsController < ApplicationController
  @user: User

  #: () -> void
  def new: () -> void

  #: () -> void
  def create: () -> void

  private

  def root_path: () -> String

  #: () -> ActionController::Parameters
  def setup_params: () -> ActionController::Parameters
end
