module TheMovieDb
  module Search
    class Base < TheMovieDb::Base
      @query: untyped

      @page: untyped

      @next_page: untyped

      @previous_page: untyped

      attr_reader query: untyped

      attr_reader page: untyped

      #  (query: String, ?page: Integer, ?api_key: String?, ?language: String?) -> void
      def initialize: (query: untyped, ?page: ::Integer, ?api_key: untyped?, ?language: untyped?) -> void

      #  (?use_cache: bool) -> untyped
      def results: (?use_cache: bool) -> untyped

      #  () -> TheMovieDb::Search::Base
      def next_page: () -> untyped

      #  () -> TheMovieDb::Search::Base
      def previous_page: () -> untyped

      private

      #  () -> ::Hash[untyped, untyped]
      def query_params: () -> untyped
    end
  end
end
