module TheMovieDb
  module Search
    class Movie < Base
      @year: untyped

      @primary_release_year: untyped

      @next_page: untyped

      @previous_page: untyped

      attr_reader year: untyped

      attr_reader primary_release_year: untyped

      #  (query: String, ?page: Integer, ?api_key: String?, ?language: String?, ?year: Integer?, ?primary_release_year: Integer?) -> void
      def initialize: (query: untyped, ?page: ::Integer, ?api_key: untyped?, ?language: untyped?, ?year: untyped?, ?primary_release_year: untyped?) -> void

      #  () -> TheMovieDb::Search::Movie
      def next_page: () -> untyped

      #  () -> TheMovieDb::Search::Movie
      def previous_page: () -> untyped

      private

      #  () -> ::Hash[untyped, untyped]
      def query_params: () -> untyped
    end
  end
end
