class Config
  class Serializer
    @data: untyped

    #  (String? json) -> Config::Serializer
    def self.load: (untyped json) -> untyped

    #  (?::Hash[untyped, untyped] data) -> void
    def initialize: (?untyped data) -> void

    #  (untyped key) -> untyped
    def []: (untyped key) -> untyped

    #  (untyped key, untyped value) -> untyped
    def []=: (untyped key, untyped value) -> untyped

    #  (untyped key) -> bool
    def key?: (untyped key) -> untyped

    # Used by Setting#contains_key? to introspect the underlying hash.
    #  () -> ::Hash[untyped, untyped]
    def marshal_dump: () -> untyped

    #  () -> ::Hash[untyped, untyped]
    def to_h: () -> untyped
  end
end
