class Config
  class Setting
    include SimplyEncrypt

    class Option < Struct[untyped]
      def self.new: (Proc default, bool encrypted) -> instance

      def default: () -> Proc
      def encrypted?: () -> bool
    end

    #: (Proc block) -> Config::Setting
    def self.call: (Proc block) -> Config::Setting

    #: (Config item, String? json) -> Config::Serializer
    def load: (Config item, String? json) -> Config::Serializer

    #: (Config item, ::Hash[untyped, untyped] object) -> String
    def dump: (Config item, ::Hash[String | Symbol, untyped] object) -> String

    #: (Symbol | String name, ?default: Proc, ?encrypted: bool) -> void
    def attribute: (Symbol | String name, ?default: Proc, ?encrypted: bool) -> void

    #: () -> ::Hash[Symbol, Config::Setting::Option]
    def attributes: () -> ::Hash[Symbol, Config::Setting::Option]

    private

    @attributes: ::Hash[Symbol, Config::Setting::Option]?

    #: (Config item, Config::Serializer object) -> Config::Serializer
    def load_attributes: (Config item, Config::Serializer object) -> Config::Serializer

    #: (Config item, ::Hash[untyped, untyped] object) -> ::Hash[untyped, untyped]
    def dump_attributes: (Config item, ::Hash[String | Symbol, untyped] object) -> ::Hash[String | Symbol, untyped]

    #: (Config item, Config::Setting::Option option) -> untyped
    def instance_exec_default: (Config item, Config::Setting::Option option) -> untyped

    #: (untyped object, Symbol key) -> bool
    def contains_key?: (Config::Serializer | ::Hash[String | Symbol, untyped] object, Symbol key) -> bool
  end
end
