class Config::Video < Config
  # Narrows the return type of Config.newest to Config::Video for this subclass.
  def self.newest: () -> Config::Video

  # These methods are dynamically defined by Config.setting in config/video.rb.
  def settings_movie_path: () -> String?
  def settings_tv_path: () -> String?
  def settings_tmdb_api_key: () -> String?
  def settings_processed_path: () -> String?

  def settings_movie_path=: (String? val) -> void
  def settings_tv_path=: (String? val) -> void
  def settings_tmdb_api_key=: (String? val) -> void
  def settings_processed_path=: (String? val) -> void

  private

  def movie_path_must_exist: () -> void
  def tv_path_must_exist: () -> void
  def tmdb_api_key_must_be_valid: () -> void
end
