module Types
  class QueryType < Types::BaseObject
    include ScopeEnforceable

    #  (id: String) -> untyped
    def node: (id: untyped) -> untyped

    #  (ids: ::Array[String]) -> ::Array[untyped]
    def nodes: (ids: untyped) -> untyped
  end
end
